// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXpNpCfz5_PvqCYq9PRl4uovVV9hvHpAU',
    appId: '1:92700967572:web:6edfadd1b34721c907aa81',
    messagingSenderId: '92700967572',
    projectId: 'pilltongapp',
    authDomain: 'pilltongapp.firebaseapp.com',
    storageBucket: 'pilltongapp.firebasestorage.app',
    measurementId: 'G-2W8NRVS8M4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXpNpCfz5_PvqCYq9PRl4uovVV9hvHpAU',
    appId: '1:92700967572:android:cd9e2b429362f0fb07aa81',
    messagingSenderId: '92700967572',
    projectId: 'pilltongapp',
    storageBucket: 'pilltongapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXpNpCfz5_PvqCYq9PRl4uovVV9hvHpAU',
    appId: '1:92700967572:ios:cbaae81f7d4e6d1807aa81',
    messagingSenderId: '92700967572',
    projectId: 'pilltongapp',
    iosBundleId: 'com.example.pilltongapp',
    storageBucket: 'pilltongapp.firebasestorage.app',
  );
}
